export interface Product {
  id: string
  name: string
  category: string
  price: number
  moq: number
  image: string
  imageAlt: string
  description: string
  slug: string
}

export const staticProducts: Product[] = [
  {
    id: "1",
    name: "Custom T-Shirts",
    category: "Apparel",
    price: 4.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom printed t-shirts for corporate branding and promotional events",
    description: "High-quality cotton t-shirts with custom screen printing or embroidery",
    slug: "custom-tshirts",
  },
  {
    id: "2",
    name: "Polo Shirts",
    category: "Apparel",
    price: 8.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Professional polo shirts with embroidered logo",
    description: "Premium cotton polo shirts perfect for corporate uniforms",
    slug: "polo-shirts",
  },
  {
    id: "3",
    name: "Baseball Caps",
    category: "Apparel",
    price: 7.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1533055640609-24b498dfd74c?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom baseball caps and promotional hats",
    description: "Adjustable baseball caps with embroidered or printed logos",
    slug: "baseball-caps",
  },
  {
    id: "4",
    name: "Hoodies",
    category: "Apparel",
    price: 18.99,
    moq: 25,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom printed hoodies and sweatshirts",
    description: "Comfortable fleece hoodies with custom branding",
    slug: "hoodies",
  },
  {
    id: "5",
    name: "Coffee Mugs",
    category: "Drinkware",
    price: 3.49,
    moq: 100,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom coffee mugs with company logo printing",
    description: "Ceramic coffee mugs with vibrant full-color printing",
    slug: "coffee-mugs",
  },
  {
    id: "6",
    name: "Water Bottles",
    category: "Drinkware",
    price: 5.99,
    moq: 100,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Branded stainless steel water bottles for corporate gifts",
    description: "Insulated stainless steel bottles that keep drinks cold for 24 hours",
    slug: "water-bottles",
  },
  {
    id: "7",
    name: "Travel Tumblers",
    category: "Drinkware",
    price: 8.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1582294522879-38f68e5d2fb2?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Insulated travel tumblers with custom logo",
    description: "Double-wall vacuum insulated tumblers for hot or cold beverages",
    slug: "travel-tumblers",
  },
  {
    id: "8",
    name: "Glass Water Bottles",
    category: "Drinkware",
    price: 9.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Eco-friendly glass water bottles with silicone sleeve",
    description: "Premium glass bottles with protective silicone sleeves",
    slug: "glass-bottles",
  },
  {
    id: "9",
    name: "USB Drives",
    category: "Tech",
    price: 6.99,
    moq: 100,
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Branded USB flash drives for data storage",
    description: "High-speed USB 3.0 flash drives with custom logo engraving",
    slug: "usb-drives",
  },
  {
    id: "10",
    name: "Power Banks",
    category: "Tech",
    price: 12.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Portable power banks with branded logo printing",
    description: "10,000mAh portable chargers with dual USB ports",
    slug: "power-banks",
  },
  {
    id: "11",
    name: "Wireless Chargers",
    category: "Tech",
    price: 15.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Wireless charging pads with custom branding",
    description: "Qi-compatible wireless charging pads for smartphones",
    slug: "wireless-chargers",
  },
  {
    id: "12",
    name: "Bluetooth Speakers",
    category: "Tech",
    price: 19.99,
    moq: 25,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Portable bluetooth speakers with logo printing",
    description: "Compact wireless speakers with impressive sound quality",
    slug: "bluetooth-speakers",
  },
  {
    id: "13",
    name: "Promotional Pens",
    category: "Office",
    price: 0.49,
    moq: 500,
    image: "https://images.unsplash.com/photo-1583483425010-c566431a7710?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Promotional pens with custom logo printing",
    description: "Smooth-writing ballpoint pens with custom imprint",
    slug: "promotional-pens",
  },
  {
    id: "14",
    name: "Notebooks",
    category: "Office",
    price: 3.99,
    moq: 100,
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom branded notebooks and journals",
    description: "Premium spiral-bound notebooks with custom cover design",
    slug: "notebooks",
  },
  {
    id: "15",
    name: "Sticky Notes",
    category: "Office",
    price: 1.99,
    moq: 250,
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom sticky notes and memo pads",
    description: "Colorful sticky note pads with custom header printing",
    slug: "sticky-notes",
  },
  {
    id: "16",
    name: "Desk Organizers",
    category: "Office",
    price: 8.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Branded desk organizers and accessories",
    description: "Multi-compartment desk organizers with logo imprint",
    slug: "desk-organizers",
  },
  {
    id: "17",
    name: "Tote Bags",
    category: "Bags",
    price: 2.99,
    moq: 250,
    image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom tote bags for promotional events and trade shows",
    description: "Durable canvas tote bags with custom screen printing",
    slug: "tote-bags",
  },
  {
    id: "18",
    name: "Backpacks",
    category: "Bags",
    price: 14.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom branded backpacks for corporate gifts",
    description: "Multi-pocket backpacks with padded laptop compartment",
    slug: "backpacks",
  },
  {
    id: "19",
    name: "Duffel Bags",
    category: "Bags",
    price: 16.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom duffel bags for gym and travel",
    description: "Spacious duffel bags with adjustable shoulder strap",
    slug: "duffel-bags",
  },
  {
    id: "20",
    name: "Laptop Bags",
    category: "Bags",
    price: 19.99,
    moq: 25,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Professional laptop bags with custom embroidery",
    description: "Padded laptop bags with multiple organizational pockets",
    slug: "laptop-bags",
  },
  {
    id: "21",
    name: "Yoga Mats",
    category: "Wellness",
    price: 12.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom branded yoga mats for wellness programs",
    description: "Non-slip yoga mats with full-color custom printing",
    slug: "yoga-mats",
  },
  {
    id: "22",
    name: "Resistance Bands",
    category: "Wellness",
    price: 4.99,
    moq: 100,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Branded resistance bands for fitness promotions",
    description: "Latex-free resistance bands in various strengths",
    slug: "resistance-bands",
  },
  {
    id: "23",
    name: "Hand Sanitizers",
    category: "Wellness",
    price: 1.49,
    moq: 500,
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom labeled hand sanitizer bottles",
    description: "2oz hand sanitizer bottles with custom label",
    slug: "hand-sanitizers",
  },
  {
    id: "24",
    name: "Fitness Towels",
    category: "Wellness",
    price: 6.99,
    moq: 100,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom embroidered gym and fitness towels",
    description: "Microfiber towels with embroidered or printed logo",
    slug: "fitness-towels",
  },
  {
    id: "25",
    name: "Throw Blankets",
    category: "Home & Garden",
    price: 14.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom fleece blankets with embroidered logo",
    description: "Soft fleece blankets perfect for corporate gifts",
    slug: "throw-blankets",
  },
  {
    id: "26",
    name: "Candles",
    category: "Home & Garden",
    price: 7.99,
    moq: 100,
    image: "https://images.unsplash.com/photo-1602874801007-bd458bb1b8b6?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom scented candles with branded labels",
    description: "Soy wax candles with custom labels and scents",
    slug: "candles",
  },
  {
    id: "27",
    name: "Coaster Sets",
    category: "Home & Garden",
    price: 4.99,
    moq: 100,
    image: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom printed coaster sets for home and office",
    description: "Cork-backed coasters with full-color printing",
    slug: "coaster-sets",
  },
  {
    id: "28",
    name: "Picnic Blankets",
    category: "Home & Garden",
    price: 16.99,
    moq: 50,
    image: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Outdoor picnic blankets with custom branding",
    description: "Waterproof picnic blankets with carrying strap",
    slug: "picnic-blankets",
  },
  {
    id: "29",
    name: "Keychains",
    category: "Other",
    price: 0.99,
    moq: 500,
    image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom metal keychains with logo engraving",
    description: "Durable metal keychains with laser engraving",
    slug: "keychains",
  },
  {
    id: "30",
    name: "Lanyards",
    category: "Other",
    price: 0.79,
    moq: 500,
    image: "https://images.unsplash.com/photo-1557687790-902ede7ab58c?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom printed lanyards for events and conferences",
    description: "Polyester lanyards with custom dye-sublimation printing",
    slug: "lanyards",
  },
  {
    id: "31",
    name: "Magnets",
    category: "Other",
    price: 1.49,
    moq: 250,
    image: "https://images.unsplash.com/photo-1560251100-38435d036b54?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom corporate magnets and souvenirs",
    description: "High-quality magnets with custom printing",
    slug: "magnets",
  },
  {
    id: "32",
    name: "Stickers",
    category: "Other",
    price: 0.29,
    moq: 1000,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800&auto=format&fit=crop",
    imageAlt: "Custom die-cut stickers and decals",
    description: "Weatherproof vinyl stickers in any shape",
    slug: "stickers",
  },
]

export const categories = [
  "All",
  "Apparel",
  "Drinkware",
  "Tech",
  "Office",
  "Bags",
  "Wellness",
  "Home & Garden",
  "Other",
]

export function getProductsByCategory(category: string): Product[] {
  if (category === "All") return staticProducts
  return staticProducts.filter((product) => product.category === category)
}

export function getProductBySlug(slug: string): Product | undefined {
  return staticProducts.find((product) => product.slug === slug)
}
